### ISSUE TITLE
Shynet on same server with Nginx and SSL

### ISSUE THREAD

**Issue by majodi** [milesmcc/shynet#199]
Is there an example or documentation on how to setup Shynet on the same server with Nginx? I installed Shynet (docker) and it is working (I can access it on http://domain:8080). But I need a proxy config so that traffic on https://domain:8080 (secure) will be forwarded to the working http Shynet.

In my 443 ssl serverblock I added several combinations of:

       location /shynet/ {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
            proxy_pass http://localhost:8080;
       }

But that doesn't work (404 resource not found).

I did see requests coming in while testing:

ERROR Invalid HTTP_HOST header: '127.0.0.1:8080'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR Invalid HTTP_HOST header: '0.0.0.0:8080'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.

I added these to ALLOWED_HOSTS and the errors are gone but I keep getting 404's

Is there an example somewhere of how to use Shynet on the same machine as the Nginx webserver?

**Comment by CasperVerswijvelt** [comment]
Hey, I think your issue might be that your location is set to `/shynet/`. Since the reverse proxy is set up at `/shynet` and shynet does not support a configurable base url (yet?) all redirects will go to http://domain directly without the `/shynet` path, which will result in a 404, as it is not defined as a nginx location block.

E.g going to `https//example.com/shynet` will redirect to `https//example.com/dashboard` instead of `https//example.com/shynet/dashboard`

Simple solution: just replace 
`location /shynet/ {` 
with 
`location / {`

If that is not possible in your case and you truly want to host it at the `/shynet` path on your domain, I'll have to disapoint you for now.

**Comment by majodi** [comment]
Clear, thank you. Yeah, not possible for my setup so for now I switched to GoAccess, enough for me right now.
