### ISSUE TITLE
Links on same domain being counted as referrers

### ISSUE THREAD

**Issue by Windyo** [milesmcc/shynet#26]
The referrer page lists pages that are hosted under the same domain that is being tracked, which I consider a bug as self-referrers aren't typically included in analytics.

Example:
![image](https://user-images.githubusercontent.com/17938171/80955755-4c98bd80-8def-11ea-9afa-a72fcfb71dbc.png)
The "blog" URL and all subpages shouldn't show up as they are pages being tracked, and therefore not really a referrer.

**Comment by milesmcc** [comment]
This is definitely unexpected behavior. Unfortunately the fix is not obvious, because Shynet can track multiple domains using the same service, and it’s sometimes the case that you do want to track referrers between those domains.

Do you think a good option would be to add an “exclude referrers” or “internal domains” list in advanced settings, where you could set which URL patterns to exclude in the the referrer list?

**Comment by Windyo** [comment]
Yeah I think that's the cleanest option - that way the user can exclude all domains, or a subpart of it.

As an added bonus it allows excluding domains that someone doesn't want to see - let's imagine you know you're getting a ton of "referrals" from one of those SEO sites, that'd allow you to exclude that from the list as well.

**Comment by milesmcc** [comment]
Thanks @Windyo! Implemented in v0.4.0.
