### ISSUE TITLE
Sessions have local IP address, country and location is unknown

### ISSUE THREAD

**Issue by agazso** [milesmcc/shynet#29]
I installed the app with `docker-container` and I use Nginx to reverse proxy it. The problem is that every session seems to be coming from a local IP address (`192.168.16.1`) therefore the country and the location is unknown. If I check this IP it belongs to the `shynet_internal` docker network.

```
$ sudo docker network ls --no-trunc
NETWORK ID          NAME                DRIVER              SCOPE
<...OMITTED...>
4fbb80aa345c        shynet_internal     bridge              local

$ sudo ifconfig 
<...OMITTED...>
br-4fbb80aa345c: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.16.1  netmask 255.255.240.0  broadcast 192.168.31.255

```

Has anyone experienced something similar?

**Comment by milesmcc** [comment]
What is your NGINX config? Have you set the proper forwarding headers? See https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/ for more info.

**Comment by agazso** [comment]
This might be the problem, I did not set any extra headers. It's not completely clear for me from the Nginx documentation what should I set. Is it the `Forwarded` header and the two mappings with the regexps?

Maybe it's a good idea to add this information to the [Usage guide](https://github.com/milesmcc/shynet/blob/master/GUIDE.md#installation)

**Comment by milesmcc** [comment]
I’ll definitely update the NGINX instructions to include forwarding.

The reason you experience this issue is that origin IP addresses aren’t inherently included in every HTTP request—your server needs to pass that information to Shynet. Gunicorn (the default front-facing webserver) does this automatically, as do most hosted reverse proxies (like Cloudflare).

Here are the HTTP headers that Shynet looks for to detect remote IP address (in order of decreasing precedence):

```python
 # The default meta precedence order
 IPWARE_META_PRECEDENCE_ORDER = (
     'HTTP_X_FORWARDED_FOR', 'X_FORWARDED_FOR',  # <client>, <proxy1>, <proxy2>
     'HTTP_CLIENT_IP',
     'HTTP_X_REAL_IP',
     'HTTP_X_FORWARDED',
     'HTTP_X_CLUSTER_CLIENT_IP',
     'HTTP_FORWARDED_FOR',
     'HTTP_FORWARDED',
     'HTTP_VIA',
     'REMOTE_ADDR',
 )
```

Django converts dashes to underscores and adds the HTTP prefix, so I recommend adding the `X-Forwarded-For` header to your NGINX conf.

Let me know if that works. If it does, would you mind posting a snippet of your working NGINX config so that I can add it to the usage guide? I don’t have much experience with NGINX, so I rely on others to test and contribute NGINX-related documentation.

**Comment by agazso** [comment]
Thanks, this was the missing information for me!

Because by default both Nginx and Django supports the `X_FORWARDED_FOR` header, it's a one-liner to fix this. You just have to add the Nginx builtin `$proxy_add_x_forwarded_for` variable to the `location` directive.

So my config looks like this and it works now:
```
location / {
    proxy_pass http://localhost:8080;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
}
```

Please note that the aforementioned Nginx documentation mentions this as legacy, nonstandard method that has been later standardized in an RFC. However as far as I understand we don't need the extensibility that the standard provides and it just works having to use the ugly regexs that come with that.

**Comment by milesmcc** [comment]
Perfect, thanks! Glad it's working. I'll update the usage guide to include this.
