### ISSUE TITLE
`script.js` being requested often during app usage

### ISSUE THREAD

**Issue by ndom91** [milesmcc/shynet#32]
So I've applied this to a few of my react applications, and i've noticed that even during non-routing based clicks / actions, script.js gets queried all the time. 

![image](https://user-images.githubusercontent.com/7415984/81968066-2ad3dd80-961c-11ea-9179-093aa1c5cd9e.png)

The request payload is identical in all of those requests.

Is there anyway to reduce the amount of requests being made? Especially if no navigation is taking place.

**Comment by milesmcc** [comment]
Unfortunately, this is not possible. It's important to note that all those repeated requests aren't the browser loading the script _again_; instead, it's the script sending a heartbeat via POST back to Shynet saying "hey, I'm still on this page!". The repeated requests is critical to how Shynet determines how long a user spends on a page, for example.

(If there's a better way to determine how long users stay on the page, please let me know, as I agree the current way is a bit clunky—but it's also how all other analytics tools I'm aware of do it.)

You can decrease the frequency at which these requests by setting the `SCRIPT_HEARTBEAT_FREQUENCY` to a very high number (e.g., `30000`, for a request only every 30 seconds).

**Comment by ndom91** [comment]
@milesmcc is the _only_ goal of these frequent requests without navigation to determine how long a user was on a page?

Because in that case you could do the initial request when the user visits the page and then listen for the `window.onbeforeunload` event when the user navigates away and diff those two measurements.

**Comment by milesmcc** [comment]
Right now, the multiple requests per page load is currently only used for determining session length and currently online users, but there are plans to use it to collect more data in the future.

That said, my concern with `window.onbeforeunload` is twofold:

- There’s no guarantee that the JS runtime won’t be terminated in time for the request to finish. Because sending POSTs is typically a two-part process (the browser sends an OPTIONS to verify the request is valid, then the POST if the OPTIONS succeeds), a significant portion of the requests will fail (in my tests in a local environment on Chrone, around 70% of onbeforeunload requests didn’t make it to my _local server_).
- Often, the gap between page load and page unload is significant—people leave tabs open for days. Shynet only remembers sessions for 30m after their last heartbeat, otherwise it’s counted as a new page load (expected behavior, because having 24h+ length sessions would really skew average duration numbers and be generally misleading). Not having persistent heartbeats would prevent Shynet from knowing which sessions are currently active versus expired (esp. considering that there’s no guarantee that onbeforeunload will fire).

What do you think? I may be missing something, but based on this I think that using onbeforeunload is pretty unworkable.

**Comment by ndom91** [comment]
So I was not very familiar with `window.beforeunload` and not aware of all these "gotchas". Anyway, it seems like you've thought this through pretty well, I definitely have no further suggestions haha.

This leads me to another question, however. What (if any) are the downsides of running shynet clients only via the image route?

**Comment by milesmcc** [comment]
The main downsides are that you wouldn’t be able to get:

- page duration information
- referrer information
- page load time information

If all that matters is total number of sessions and the most visited pages, though, using just the image tracker is a viable option.
