### ISSUE TITLE
Error 500 when sending mail

### ISSUE THREAD

**Issue by notarobot63** [milesmcc/shynet#47]
Hello,
I'm using Shynet with docker compose on Ubuntu 20.04 and I have an error when I try to send the verification email.
The browser show me a "Server Error (500)" message.
[Here](https://notarobot.xyz/zerobin/?9fc7d8a58ad4a17c#AzTkF6aGnbDZAdXup1Fp8gJNwFZXhiYHFrjPNtZWnJos) are the logs.
Thanks for your help !

**Comment by milesmcc** [comment]
Does your SMTP email provider use TLS? Could you provide more information about your configuration/environment so we can isolate the issue?

**Comment by notarobot63** [comment]
Hello, yes my server uses STARTTLS on port 587

**Comment by milesmcc** [comment]
Could you please provide more information about your environment? For example, could you provide a redacted version of your environment file?

**Comment by notarobot63** [comment]
Shynet is running via docker compose on a Ubuntu 20.04 Server VM and is then served through Nginx reverse proxy. Mail server is external and my own, but Shynet mail don't even leave the container so I doubt the probleme is here.

Did you look at the logs I provided ?
[Here](https://notarobot.xyz/zerobin/?8982d97754a26e4d#5LKpbvaLRusHFJSct9rrjBsAJteqvKuNjs1KyWrB2dxp) is my .env file.

**Comment by milesmcc** [comment]
Yes, I saw the logs. The env file that you sent is password protected, though, so I can’t see it. 

Unfortunately it really does look like the SSL on your web server is misconfigured; Shynet uses Django’s email implementation, so the issue is almost certainly unrelated to Shynet.

Unless others can replicate the issue on their machines (which I’ve attempted to do for this email error unsuccessfully), there’s really nothing I can do to help here. Sorry.
