### ISSUE TITLE
Updating Config

### ISSUE THREAD

**Issue by assman** [milesmcc/shynet#83]
Hi, very nice project. Deployed it to the cloud and loving it so far. 

Just wanted to check how do we put into effect some changes that we make to the `.env` file?

**Comment by milesmcc** [comment]
You should be able to just restart the server; the environment variables are read when Shynet starts up. Depending on how you deployed Shynet, this might mean stopping it with docker-compose, Docker, or Kubernetes.

Let me know if this answers your question. Sorry I can't be more specific! Because there are many ways to deploy Shynet, it's hard to give concrete instructions.

**Comment by assman** [comment]
Understood. I stopped the docket container and ran it again after updating the `.env` file using the `docker run` command. Thanks!

**Comment by milesmcc** [comment]
Great!
