### ISSUE TITLE
Percentiles not shown in stats

### ISSUE THREAD

**Issue by seriousm4x** [milesmcc/shynet#85]
![image](https://user-images.githubusercontent.com/23456686/93691477-05813f80-fae6-11ea-8ffd-b894c5cfb779.jpeg)

I think the image is self explanatory. There are no errors printed to the logs, therefore they wouldn't be helpful. I've had this issue since I started using shynet, but never really cared about it. Im running shynet in docker, have "Respect DNT" disabled (if that's important).
I got 2 pages running but it doesn't show on both of them.

**Comment by milesmcc** [comment]
Thanks for opening an issue!

Looking at your screenshots, this is usually the case when you create a new site. Because there's no historical data to compare against, it can't generate stats for loadtime, bounce rate, duration, and hits/session. If you change the time period to something smaller (e.g., 1 day), do you then see the delta percentages?

**Comment by seriousm4x** [comment]
Oh ok. Like you said, if I change it to a smaller time range it shows. As I can tell the default time range is a whole month, right? Maybe if data doesn't exist for a whole month, change the start day to the first day with valid data?

**Comment by milesmcc** [comment]
That’s right — the percentages will start showing after the site has existed for more than a month (so there is data to build the percentages from). I’m going to close this issue because I think we’ve resolved everything, but let me know if anything else is unclear.
