### ISSUE TITLE
Create Docker image for ARMv7 architecture

### ISSUE THREAD

**Issue by ducula** [milesmcc/shynet#96]
Hi, I'm interested in running Shynet on a Raspberry Pi but it seems that the Docker image only runs on AMD64 devices. It would be nice to run it on a Pi.

**Comment by milesmcc** [comment]
Hmm, interesting. Do you have any idea how we might set this up? We currently use a pretty standard base image, so I see no reason why portability should be an issue from a development standpoint.

**Comment by VeryStrongFingers** [comment]
@milesmcc building images using the official Docker GitHub action has support for multi-arch builds
https://github.com/marketplace/actions/build-and-push-docker-images

are you currently building/tagging/pushing images manually at present?

**Comment by milesmcc** [comment]
It’s all done on Docker Hub through their CI

**Comment by rotoclone** [comment]
I was able to get Shynet running on my Raspberry Pi by doing this (all these steps were run on the Raspberry Pi):
1. Clone the repo and `cd` into it
2. Edit the first line of `Dockerfile`, replacing `FROM python:3-alpine` with `FROM python:alpine3.12` (this is needed because [apparently there's some ipv6-related issue with Alpine 3.13 on Raspberry Pi](https://github.com/gliderlabs/docker-alpine/issues/386#issuecomment-804748888))
3. Run `docker build -t armshynet . --network=host` (this builds an ARMv7 docker image and tags it with `armshynet`)
4. Edit the `shynet` service entry in `docker-compose.yml`, replacing `image: milesmcc/shynet:latest` with `image: armshynet:latest`
5. Follow the steps from [the docker-compose installation guide](https://github.com/milesmcc/shynet/blob/master/GUIDE.md#basic-installation-with-docker-compose) as normal

Also, I'm not sure if this is Shynet-related, but I had some network issues on my Raspberry Pi when the Docker service was enabled, causing Shynet (and any other services running on the Pi) to not be accessible from outside the Pi. I fixed it by creating an `/etc/docker/daemon.json` file with the following contents:
```json
{
    "iptables": false,
    "bridge": "none"
}
```

**Comment by Kovah** [comment]
I recently added ARM Docker images for LinkAce. Unfortunately, the Docker Hub is currently not able to build those images. You would have to do this through Github (or another CI provider). I have chosen Github Actions as the testing is run by it. You can find the workflow for Linkace [here](https://github.com/Kovah/LinkAce/blob/main/.github/workflows/build-docker.yml).
It's not that complicated, but I would suggest trying this for one or more releases with a test repository before flipping the switch. Currently, there are no issues with the build process at Linkace.
If you need any help feel free to contact me. 👍

**Comment by CasperVerswijvelt** [comment]
@Kovah awesome! Your GitHub actions worked basically out of the box and I was able to have GitHub build and push the images to Docker Hub.

PR here: #131
